### ISSUE TITLE
Expand `Running the App` section in README

### ISSUE THREAD

**Issue by SalocinHB** [bobokun/actualtap-py#24]
Currently, the section on running the app doesn't include any hints on actually running the app:

> Running the App
> 
> To run Actual Tap locally (i.e. for development or not containerised):
> 
> $ cp config/config.yml.sample config/config.yml
> Edit the config.yml file accordingly

What do I need to execute to actually _run the app_?

**Comment by bobokun** [comment]
to run it locally you can run `uvicorn main:app --host 0.0.0.0`
