### ISSUE TITLE
Docker container won't start since v0.1.3

### ISSUE THREAD

**Issue by mearl72** [bobokun/actualtap-py#27]
First of all, thank you for this project. It had been working for a while. Only recently have I had two different issues, one of which I don't have a workaround currently. I will create a separate issue for the other as they are unrelated I believe.

I have been using v0.1.2 as upgrading to either v0.1.3 or v0.1.4 throw the following when utilizing docker.

```Traceback (most recent call last):
  File "/usr/local/bin/fastapi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/cli.py", line 12, in main
    raise RuntimeError(message)  # noqa: B904
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: To use the fastapi command, please install "fastapi[standard]":

        pip install "fastapi[standard]"

File config.yml.sample is up to date
To use the fastapi command, please install "fastapi[standard]":

        pip install "fastapi[standard]"

**Comment by bobokun** [comment]
This is fixed in the latest release
