### ISSUE TITLE
Failed to update transaction

### ISSUE THREAD

**Issue by mearl72** [bobokun/actualtap-py#28]
I am currently using v0.1.2 via Docker due to what I've stated in issue #27.

I'm getting the following error when running the shortcut `Wallet to ActualTap Py`:

```
Failed to update transaction:
{"detail":"UNIQUE constraint failed: dashboard.id"}
```

No transactions have been adding as I've been getting this error or just a generic `Failed to update transaction`.

This started happening after Actual's release to version 24.9.0. I hadn't used my phone to pay until about a week later and noticed a few days after that that transactions weren't being added.

**Comment by bobokun** [comment]
This is fixed in the latest release
