### ISSUE TITLE
Error message about unsupported table

### ISSUE THREAD

**Issue by hrpomrx** [bobokun/actualtap-py#32]
Getting the following back when the iOS shortcut automation runs:

{"detail":"Actual found a table not supported by the library: table 'preferences' not found\n"}

Error seems to be coming from actualpy,

**Comment by hrpomrx** [comment]
Update: I was able to fix this by creating a new sync id, some built-in table name evidently got changed recently. I also built a new Docker image locally due to an enum validation error for imported_payee with the latest one from the ghcr.io container repo; I presume actualpy has not been updated on that image. Anyway, card taps get uploaded now.

**Comment by bobokun** [comment]
This should be fixed in the latest release
